import type { Template } from '../../shared/types';

/**
 * Each template combines a distinct font stack, frame style, shadow/glow
 * choice, chrome (progress / play icon / waveform), and decoration so the
 * gallery offers visibly different looks. Rendering is fully driven by these
 * fields — the shared scene renderer in src/shared/scene.ts paints whatever
 * the template says.
 *
 * IMPORTANT: do NOT clone Spotify / Apple Music / YouTube Music UI or logos.
 * Those templates share only a color/feel hint with the named services.
 */

const minimalWhite: Template = {
  id: 'minimal-white',
  name: '미니멀 화이트',
  description: '깨끗한 흰 톤, 큰 검정 가사',
  fontFamily: '"Inter", "Pretendard", sans-serif',
  fontStack: {
    base: '"Inter", "Pretendard"',
    byLang: {
      ko: '"Pretendard", "Apple SD Gothic Neo"',
      ja: '"Noto Sans JP"',
      zh: '"Noto Sans SC"',
    },
  },
  fontSize: 64,
  fontWeight: 700,
  lyricPosition: 'bottom',
  lyricColor: '#111111',
  lyricSubColor: '#FFB300',
  lyricAlign: 'center',
  showPlayerControl: false,
  showWaveform: false,
  progressBarStyle: 'thin',
  backgroundEffect: 'blur',
  animationStyle: 'fade',
  cardBg: '#FFFFFF',
  // 0.85 made the entire frame look like a giant white card hiding the
  // photo. Lowered so the upload reads through clearly while the white
  // mood is still felt at the lyric band.
  overlayOpacity: 0.25,
  frameStyle: 'rounded',
  frameColor: '#FFFFFF',
  shadowStyle: 'soft',
  playIconStyle: 'minimal',
  decoration: 'none',
  motionPreset: 'slow_zoom_in',
  animationPreset: 'fade',
  reactiveMode: 'soft_pulse',
  cinematicFxPreset: 'clean_cinematic',
};

const darkMusicPlayer: Template = {
  id: 'dark-music-player',
  name: '다크 뮤직 플레이어',
  description: '진한 어둠 + 굵은 자막 + 재생 컨트롤',
  fontFamily: '"Inter", sans-serif',
  fontStack: {
    base: '"Inter"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 58,
  fontWeight: 700,
  lyricPosition: 'bottom',
  lyricColor: '#FFFFFF',
  lyricSubColor: '#FFD60A',
  lyricAlign: 'center',
  showPlayerControl: true,
  showWaveform: false,
  progressBarStyle: 'rounded',
  backgroundEffect: 'darken',
  animationStyle: 'slide',
  cardBg: '#0a0a0c',
  overlayOpacity: 0.35,
  frameStyle: 'rounded',
  frameColor: '#1f1f29',
  shadowStyle: 'soft',
  playIconStyle: 'rounded',
  decoration: 'none',
  motionPreset: 'float_soft',
  animationPreset: 'blur_fade',
  reactiveMode: 'cinematic_bloom',
  cinematicFxPreset: 'subtle_bloom',
};

const spotifyInspired: Template = {
  id: 'spotify-inspired',
  name: 'Spotify 스타일',
  description: '스트리밍 플레이어 느낌, 좌측 정렬 큰 글씨 (자체 디자인)',
  fontFamily: '"Inter", sans-serif',
  fontStack: {
    base: '"Inter", "SF Pro Display"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 60,
  fontWeight: 800,
  lyricPosition: 'bottom',
  lyricColor: '#FFFFFF',
  lyricSubColor: '#1DB954',
  lyricAlign: 'left',
  showPlayerControl: true,
  showWaveform: false,
  progressBarStyle: 'thin',
  backgroundEffect: 'darken',
  animationStyle: 'fade',
  cardBg: '#121212',
  overlayOpacity: 0.35,
  frameStyle: 'rounded',
  frameColor: '#181818',
  shadowStyle: 'soft',
  playIconStyle: 'rounded',
  decoration: 'none',
  motionPreset: 'slow_zoom_in',
  animationPreset: 'slide_up',
  reactiveMode: 'waveform_boost',
  cinematicFxPreset: 'subtle_bloom',
  playerChrome: 'spotify-like',
};

const appleMusicInspired: Template = {
  id: 'apple-music-inspired',
  name: 'Apple Music 스타일',
  description: '풀 컬러 배경 + 거대 타이포 (자체 디자인)',
  fontFamily: '"SF Pro Display", "Inter", sans-serif',
  fontStack: {
    base: '"SF Pro Display", "Inter"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 72,
  fontWeight: 800,
  lyricPosition: 'bottom',
  lyricColor: '#FFFFFF',
  lyricSubColor: '#FF2D55',
  lyricAlign: 'left',
  showPlayerControl: false,
  showWaveform: false,
  progressBarStyle: 'thick',
  backgroundEffect: 'none',
  animationStyle: 'slide',
  cardBg: '#000000',
  overlayOpacity: 0.35,
  frameStyle: 'rounded',
  frameColor: '#000000',
  shadowStyle: 'hard',
  playIconStyle: 'minimal',
  decoration: 'none',
  motionPreset: 'pan_left',
  animationPreset: 'fade',
  reactiveMode: 'cinematic_bloom',
  cinematicFxPreset: 'soft_blur',
  playerChrome: 'apple-like',
};

const youtubeMusicInspired: Template = {
  id: 'youtube-music-inspired',
  name: 'YouTube Music 스타일',
  description: '레드 포인트 + 원형 앨범 (자체 디자인)',
  fontFamily: '"Inter", sans-serif',
  fontStack: {
    base: '"Inter", "Roboto"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 54,
  fontWeight: 700,
  lyricPosition: 'center',
  lyricColor: '#FFFFFF',
  lyricSubColor: '#FF0033',
  lyricAlign: 'center',
  showPlayerControl: true,
  showWaveform: true,
  progressBarStyle: 'rounded',
  backgroundEffect: 'darken',
  animationStyle: 'fade',
  cardBg: '#0f0f0f',
  overlayOpacity: 0.35,
  // Phase 5-3: was 'circle' which clipped the user's photo into a small
  // round mask — biggest single anti-cover offender per beta feedback.
  // Switched to 'rounded' so the rectangular photo dominates and the
  // YouTube-Music-feel comes from the playerChrome card alone.
  frameStyle: 'rounded',
  frameColor: '#0f0f0f',
  shadowStyle: 'soft',
  playIconStyle: 'rounded',
  decoration: 'none',
  motionPreset: 'float_soft',
  animationPreset: 'soft_pop',
  reactiveMode: 'soft_pulse',
  cinematicFxPreset: 'clean_cinematic',
  playerChrome: 'youtube-like',
};

const polaroidMood: Template = {
  id: 'polaroid-mood',
  name: '폴라로이드 무드',
  description: '폴라로이드 테두리 + 잔잔한 웨이브',
  fontFamily: '"Caveat", "Pretendard", cursive',
  fontStack: {
    base: '"Caveat", "Pretendard"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 56,
  fontWeight: 600,
  lyricPosition: 'top',
  lyricColor: '#1A1A1A',
  lyricSubColor: '#E76F51',
  lyricAlign: 'center',
  showPlayerControl: false,
  showWaveform: true,
  progressBarStyle: 'none',
  backgroundEffect: 'sepia',
  animationStyle: 'none',
  cardBg: '#F5EFE0',
  overlayOpacity: 0.2,
  frameStyle: 'polaroid',
  framePadding: 0.025,
  frameColor: '#FFFCF2',
  shadowStyle: 'soft',
  playIconStyle: 'none',
  decoration: 'grain',
  motionPreset: 'slow_zoom_out',
  animationPreset: 'slide_down',
  reactiveMode: 'soft_pulse',
  cinematicFxPreset: 'dust_grain',
};

const cassetteTape: Template = {
  id: 'cassette-tape',
  name: '카세트 테이프',
  description: '레트로 카세트 + 릴 장식',
  fontFamily: '"Bebas Neue", "Inter", sans-serif',
  fontStack: {
    base: '"Bebas Neue", "Inter"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 52,
  fontWeight: 700,
  lyricPosition: 'center',
  lyricColor: '#FFEFC8',
  lyricSubColor: '#FF6F61',
  lyricAlign: 'center',
  showPlayerControl: false,
  showWaveform: false,
  progressBarStyle: 'thick',
  backgroundEffect: 'sepia',
  animationStyle: 'none',
  cardBg: '#3b2a1a',
  overlayOpacity: 0.3,
  frameStyle: 'cassette',
  frameColor: '#d8b984',
  shadowStyle: 'hard',
  playIconStyle: 'triangle',
  decoration: 'reels',
  motionPreset: 'pan_right',
  animationPreset: 'soft_pop',
  reactiveMode: 'waveform_boost',
  cinematicFxPreset: 'film_texture',
};

const vhsNight: Template = {
  id: 'vhs-night',
  name: 'VHS 야간',
  description: '심야 VHS 노이즈 + 스캔라인',
  fontFamily: '"VT323", "Inter", monospace',
  fontStack: {
    base: '"VT323", "IBM Plex Mono", monospace',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 56,
  fontWeight: 700,
  lyricPosition: 'bottom',
  lyricColor: '#E0FFFF',
  lyricSubColor: '#FF66FF',
  lyricAlign: 'center',
  showPlayerControl: false,
  showWaveform: true,
  progressBarStyle: 'thin',
  backgroundEffect: 'darken',
  animationStyle: 'fade',
  cardBg: '#0a0014',
  overlayOpacity: 0.4,
  frameStyle: 'photo',
  frameColor: '#1c1c2e',
  shadowStyle: 'glow',
  glowColor: '#FF66FF',
  playIconStyle: 'minimal',
  decoration: 'scanlines',
  motionPreset: 'pan_right',
  animationPreset: 'blur_fade',
  reactiveMode: 'cinematic_bloom',
  cinematicFxPreset: 'aberration_grain',
};

const softKpopLyric: Template = {
  id: 'soft-kpop-lyric',
  name: '소프트 K-팝 가사',
  description: '파스텔 무드 + 반짝이 장식',
  fontFamily: '"Pretendard", "Inter", sans-serif',
  fontStack: {
    base: '"Pretendard", "Inter"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 60,
  fontWeight: 700,
  lyricPosition: 'bottom',
  lyricColor: '#FFFFFF',
  lyricSubColor: '#FFD8E8',
  lyricAlign: 'center',
  showPlayerControl: false,
  showWaveform: false,
  progressBarStyle: 'thin',
  backgroundEffect: 'blur',
  animationStyle: 'fade',
  // Soft pink mood, but cardBg now only shows in lyric band — photo
  // dominates. Tint dropped from 0.5 so the upload isn't pink-washed.
  cardBg: '#FFB7C5',
  overlayOpacity: 0.25,
  frameStyle: 'rounded',
  frameColor: '#FFE6F0',
  shadowStyle: 'soft',
  playIconStyle: 'none',
  decoration: 'sparkles',
  motionPreset: 'float_soft',
  animationPreset: 'soft_pop',
  reactiveMode: 'lyric_glow',
  cinematicFxPreset: 'soft_blur',
};

const neonDrive: Template = {
  id: 'neon-drive',
  name: '네온 드라이브',
  description: '네온 사이버펑크 글로우 테두리',
  fontFamily: '"Orbitron", "Inter", sans-serif',
  fontStack: {
    base: '"Orbitron", "Inter"',
    byLang: { ko: '"Pretendard"' },
  },
  fontSize: 60,
  fontWeight: 800,
  lyricPosition: 'center',
  lyricColor: '#00FFD1',
  lyricSubColor: '#FF00C8',
  lyricAlign: 'center',
  showPlayerControl: true,
  showWaveform: true,
  progressBarStyle: 'rounded',
  backgroundEffect: 'darken',
  animationStyle: 'slide',
  cardBg: '#06061a',
  overlayOpacity: 0.4,
  frameStyle: 'neon-border',
  frameColor: '#00FFD1',
  glowColor: '#FF00C8',
  shadowStyle: 'glow',
  playIconStyle: 'rounded',
  decoration: 'none',
  motionPreset: 'slow_zoom_in',
  animationPreset: 'karaoke_glow',
  reactiveMode: 'neon_pulse',
  cinematicFxPreset: 'bloom_neon',
};

export const templates: Template[] = [
  minimalWhite,
  darkMusicPlayer,
  spotifyInspired,
  appleMusicInspired,
  youtubeMusicInspired,
  polaroidMood,
  cassetteTape,
  vhsNight,
  softKpopLyric,
  neonDrive,
];

export function getTemplate(id: string): Template {
  return templates.find((t) => t.id === id) ?? templates[0];
}
